#!/bin/bash

echo "========================================="
echo "📦 CocoaPods安装命令"
echo "========================================="
echo ""
echo "请在终端中依次运行以下命令："
echo ""
echo "========================================="
echo ""
echo "# 1. 安装CocoaPods（需要输入密码）"
echo "sudo gem install cocoapods"
echo ""
echo "# 2. 设置CocoaPods（首次需要，可能需要几分钟）"
echo "pod setup"
echo ""
echo "# 3. 验证安装"
echo "pod --version"
echo ""
echo "========================================="
echo ""
echo "# 4. 安装iOS项目依赖"
echo "cd /Users/huangm5/Desktop/opencode/zhongyimedic/mobile_app/ios"
echo "pod install"
echo ""
echo "========================================="
echo ""
echo "# 5. 在Xcode中运行应用"
echo "open ios/Runner.xcworkspace"
echo "# 然后在Xcode中选择设备并点击 ▶️"
echo ""
echo "========================================="
echo ""
